### ISSUE TITLE
Perk progression gets stuck on level 6

### ISSUE THREAD

**Issue by sebastian-palma** [poosh/KF-ScrnBalance#13]
Is there a place where to refer about perk progression and/or the ServerPerk mut being used?

Currently the perks aren't getting improvements after passing the level 6. What I mean is, the bonuses for each level doesn't change when reaching a level up the 6th one.

I can see that certain bonuses are X% damage, but once getting the next level that bonus doesn't increase. It happens with all perks.

Is there something I'm omitting?

**Comment by Duckbuster** [comment]
Hey!

Please check out the ScrnBalanceSrv.ini. 
https://github.com/poosh/KF-ScrnBalance/blob/master/ScrnBalanceSrv.ini#L130
Starting from line 130 are the level settings.

These settings you are describing are done intentionally. 

The BonusLevel*Max ones are the ones you need to change.
(or just uncomment that block that is premade with them set to max 70. DONT GO OVER 70)

But I would recommend against it, since it will make that game pretty unbalanced.
And Scrn does auto extra bonus levels when you are with teamsizes 7 and up. (its called bDynamicLevelCap, enabled by default)

Hope this helps :)

**Comment by sebastian-palma** [comment]
Thank you! Sure it helps, I'm gonna take a look at those lines.

(closing because the answer is pretty clear)
